name: onsite_erp_mobile
description: "Onsite Clone: Full-Stack Construction Management ERP & Workforce Platform"
publish_to: 'none'
version: 3.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management & DI
  provider: ^6.1.2
  
  # Networking & Real-Time
  dio: ^5.4.3+1
  socket_io_client: ^3.0.2
  connectivity_plus: ^6.0.3
  
  # Local Storage & Offline Engine
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.3
  
  # AI, Geolocation & Camera
  camera: ^0.10.5+9
  geolocator: ^11.0.0
  google_mlkit_face_detection: ^0.10.0
  
  # UI & Media
  intl: ^0.19.0
  image_picker: ^1.1.1
  syncfusion_flutter_pdfviewer: ^28.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
